# Site customizations

# Site Title
title: blog.jimurrito.com
description: A blog for all the things

# Theme setup
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
- jekyll-remote-theme